// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0m-OSWqF1kNV2p-oEuvrLSXroK7EC3mM',
    appId: '1:825337054416:web:c2e2717884a0c2aceb8ad5',
    messagingSenderId: '825337054416',
    projectId: 'todo-75025',
    authDomain: 'todo-75025.firebaseapp.com',
    storageBucket: 'todo-75025.appspot.com',
    measurementId: 'G-KEPG4ZPXM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgQT0QcTPAcaIFuZfJ-Wr1kYyahhlLCnE',
    appId: '1:825337054416:android:2aa8c3e59c0cd201eb8ad5',
    messagingSenderId: '825337054416',
    projectId: 'todo-75025',
    storageBucket: 'todo-75025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChtv-d4tU8kikQwRGlDubOkeEZ7hXoTtQ',
    appId: '1:825337054416:ios:d751a4273bc27d2beb8ad5',
    messagingSenderId: '825337054416',
    projectId: 'todo-75025',
    storageBucket: 'todo-75025.appspot.com',
    iosClientId: '825337054416-6gei5braikqle9rq808eo24dsjcsoltl.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChtv-d4tU8kikQwRGlDubOkeEZ7hXoTtQ',
    appId: '1:825337054416:ios:64a62f9e7bc86e57eb8ad5',
    messagingSenderId: '825337054416',
    projectId: 'todo-75025',
    storageBucket: 'todo-75025.appspot.com',
    iosClientId: '825337054416-b5uceatbqqld4h865ngk7hdsg1l213tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
